version: '3'
services:
  weather-service:
    container_name: "weather-app"
    build:
      context: weather_service
      dockerfile: Dockerfile
    volumes:
      - raw-data-volume:/data/raw:rw
    networks:
      - weather-analytics-network
  spark-service:
    depends_on:
      - weather-service
    container_name: "spark-job"
    restart: always
    build:
      context: spark_service
      dockerfile: Dockerfile
    volumes:
      - raw-data-volume:/data/raw:ro
      - trusted-data-volume:/data/trusted:rw
    networks:
      - weather-analytics-network
    healthcheck:
      test: [ "CMD-SHELL", "test -f /data/raw/_SUCCESS" ]
      interval: 20s
      retries: 6
      timeout: 2m
    command:
      [
        "spark-submit",
        "weather_job.py",
        "file:///data/raw",
        "file:///data/trusted"
      ]

volumes:
  raw-data-volume:
  trusted-data-volume:
networks:
  weather-analytics-network:
